### ISSUE TITLE
Add support for multiple LDAP servers

### ISSUE THREAD

**Issue by Schoaf** [zakkak/qa-ldap-login#24]
Hi,
in our company we have multiple LDAP servers, multiple domains, ... 
Do you see any way of supporting multiple LDAP servers? I would like to help, but I really have no idea about the LDAP stuff. All I know is that Jira and Apache seem to support multiple LDAP servers (different users and everything...) to authenticate against.
Maybe if you push me in the right direction, I could make the code change and test it in our company.

**Comment by zakkak** [comment]
Hi @Schoaf, I guess one approach is to test the LDAP servers iteratively. That is, 1st you try and authenticate the user against the first available server. If that fails you proceed to the second server, etc.

Programmatically it shouldn't be that hard. You just need to define an array of servers instead of a single server and then go through each of them and try to authenticate your user. If they all fail then the user cannot be authenticated. If any of them succeeds then the user gets authenticated.
